# Generated by Django 3.2.9 on 2022-10-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Niveles', '0001_initial'),
        ('Estudiantes_Profesores', '0007_auto_20221007_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiantes_Profesores.estudiante')),
                ('profesor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiantes_Profesores.profesor')),
            ],
            options={
                'db_table': 'clases',
            },
        ),
        migrations.CreateModel(
            name='Picadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del picadero')),
                ('max_estudiantes', models.IntegerField(verbose_name='maximo de estudiantes')),
                ('max_profesores', models.IntegerField(verbose_name='maximo de profesores')),
                ('nivel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Niveles.nivel')),
            ],
            options={
                'db_table': 'picaderos',
            },
        ),
        migrations.CreateModel(
            name='InfoPicadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('clase', models.ManyToManyField(to='Picaderos.Clase')),
                ('picadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Picaderos.picadero')),
            ],
            options={
                'db_table': 'infoPicaderos',
            },
        ),
    ]
