# Generated by Django 3.2.9 on 2022-10-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0002_picadero_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picadero',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
