# Generated by Django 3.2.9 on 2022-10-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0007_auto_20221007_1230'),
        ('Picaderos', '0003_alter_picadero_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiantes_Profesores.estudiante'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiantes_Profesores.profesor'),
        ),
    ]
