# Generated by Django 3.2.9 on 2022-10-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niveles', '0001_initial'),
        ('Picaderos', '0004_auto_20221007_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picadero',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Niveles.nivel'),
        ),
    ]
