# Generated by Django 3.2.9 on 2022-10-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0007_auto_20221007_1230'),
        ('Picaderos', '0005_alter_picadero_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='clase',
            name='estudiante',
            field=models.ManyToManyField(to='Estudiantes_Profesores.Estudiante'),
        ),
        migrations.RemoveField(
            model_name='clase',
            name='profesor',
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ManyToManyField(to='Estudiantes_Profesores.Profesor'),
        ),
    ]
