# Generated by Django 3.2.9 on 2022-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0008_auto_20221013_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopicadero',
            name='hora',
            field=models.TimeField(unique=True),
        ),
    ]
