# Generated by Django 3.2.9 on 2022-10-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0009_alter_infopicadero_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopicadero',
            name='hora',
            field=models.TimeField(),
        ),
    ]
