# Generated by Django 3.2.9 on 2022-10-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0010_alter_infopicadero_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopicadero',
            name='dia',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('0', 'Domingo')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
