# Generated by Django 3.2.9 on 2022-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0012_alter_picadero_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopicadero',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
