# Generated by Django 3.2.9 on 2022-10-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0015_alter_clase_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='estudiante',
            new_name='clase',
        ),
    ]
