# Generated by Django 3.2.9 on 2022-10-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0017_rename_clase_clase_calendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('InfoPicadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Picaderos.infopicadero')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Picaderos.clase')),
            ],
        ),
        migrations.RemoveField(
            model_name='infopicadero',
            name='clases',
        ),
        migrations.AddField(
            model_name='infopicadero',
            name='clases',
            field=models.ManyToManyField(through='Picaderos.EstadoClase', to='Picaderos.Clase'),
        ),
    ]
