# Generated by Django 3.2.9 on 2022-10-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0018_auto_20221028_1146'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clase',
            table='clasesOlvidadas',
        ),
        migrations.AlterModelTable(
            name='estadoclase',
            table='clases',
        ),
    ]
