# Generated by Django 4.1 on 2022-10-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Picaderos", "0019_auto_20221028_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="estadoclase",
            name="dia",
            field=models.DateField(default='1900-02-11'),
            preserve_default=False,
        ),
    ]
