# Generated by Django 3.2.9 on 2022-10-31 01:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0023_calendario_estado'),
        ('Picaderos', '0019_auto_20221028_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoclase',
            name='dia',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 20, 40, 3, 522428)),
        ),
        migrations.AlterField(
            model_name='clase',
            name='calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes_Profesores.calendario'),
        ),
        migrations.AlterModelTable(
            name='estadoclase',
            table='HistorialClases',
        ),
    ]
