# Generated by Django 4.1 on 2022-10-30 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Picaderos", "0020_auto_20221030_2040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoclase",
            name="dia",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 30, 14, 30, 30, 229111)
            ),
        ),
    ]
