# Generated by Django 4.1 on 2022-10-30 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Picaderos", "0021_alter_estadoclase_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoclase",
            name="dia",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 30, 14, 52, 59, 507540)
            ),
        ),
        migrations.AlterModelTable(
            name="estadoclase",
            table="HistorialDeClases",
        ),
    ]
