# Generated by Django 4.1 on 2022-10-30 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0023_calendario_estado"),
        ("Picaderos", "0023_alter_estadoclase_dia_alter_estadoclase_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clase",
            name="calendario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Estudiantes_Profesores.calendario",
            ),
        ),
        migrations.AlterField(
            model_name="estadoclase",
            name="dia",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 30, 15, 53, 31, 775907)
            ),
        ),
    ]
