# Generated by Django 3.2.9 on 2022-10-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0020_auto_20221030_2040'),
        ('Picaderos', '0024_alter_clase_calendario_alter_estadoclase_dia'),
    ]

    operations = [
    ]
