# Generated by Django 3.2.9 on 2022-10-31 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0025_merge_20221031_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoclase',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadoclase',
            name='dia',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 11, 31, 28, 867265)),
        ),
    ]
