# Generated by Django 3.2.9 on 2022-10-31 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0026_auto_20221031_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoclase',
            name='dia',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 16, 37, 29, 701942, tzinfo=utc)),
        ),
    ]
