# Generated by Django 4.1 on 2022-10-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="aceptaContrato",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="comprobante_documento_identidad",
            field=models.BooleanField(
                verbose_name="tiene comprobante de documento de identidad"
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="comprobante_seguro_medico",
            field=models.BooleanField(
                verbose_name="tiene comprobante de seguro medico"
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="poliza",
            field=models.CharField(max_length=150, verbose_name="poliza"),
        ),
    ]
