# Generated by Django 3.2.9 on 2022-09-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('1', 'Asistió'), ('2', 'No asistió'), ('3', 'Cancelo con excusa'), ('4', 'Cancelo por enfermedad')], max_length=15),
        ),
    ]
