# Generated by Django 4.1 on 2022-09-12 19:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="diaClase",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("1", "Lunes"),
                    ("2", "Martes"),
                    ("3", "Miércoles"),
                    ("4", "Jueves"),
                    ("5", "Viernes"),
                    ("6", "Sábado"),
                    ("7", "Domingo"),
                ],
                max_length=10,
            ),
        ),
    ]
