# Generated by Django 4.1 on 2022-08-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagado", models.BooleanField(default=False)),
                ("diaClases", models.DateField()),
                ("horaClases", models.TimeField()),
                ("mesesPagados", models.IntegerField()),
                (
                    "estudiante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estudiantes_Profesores.estudiante",
                    ),
                ),
            ],
            options={"db_table": "registros",},
        ),
    ]
