# Generated by Django 4.1 on 2022-09-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0002_alter_registro_diaclase"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="estado",
            field=models.BooleanField(default=True),
        ),
    ]
