# Generated by Django 4.1 on 2022-09-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0002_registro_diaclase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="diaClase",
            field=models.CharField(
                choices=[
                    (1, "Lunes"),
                    (2, "Martes"),
                    (3, "Miércoles"),
                    (4, "Jueves"),
                    (5, "Viernes"),
                    (6, "Sábado"),
                    (7, "Domingo"),
                ],
                max_length=10,
            ),
        ),
    ]
