# Generated by Django 4.1 on 2022-09-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0003_estudiante_estado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor", options={"verbose_name_plural": "profesores"},
        ),
    ]
