# Generated by Django 3.2.9 on 2022-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0003_auto_20220929_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_clase',
            field=models.CharField(choices=[('1', 'Asistió'), ('2', 'No asistió'), ('3', 'Cancelo con excusa'), ('4', 'Cancelo por enfermedad')], max_length=15),
        ),
    ]
