# Generated by Django 3.2.9 on 2022-09-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0004_alter_estudiante_tipo_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('1', 'Asistió'), ('2', 'No asistió'), ('3', 'Cancelo con excusa'), ('4', 'Cancelo por enfermedad')], max_length=15),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_clase',
            field=models.CharField(choices=[('1', 'Clase puntual'), ('2', 'Mensualidad')], max_length=15),
        ),
    ]
