# Generated by Django 3.2.9 on 2022-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0004_auto_20221006_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='barrio_A',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='barrio de resdencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_madre',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='numero de cedula de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_padre',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='numero de cedula del padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular_madre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numero de celular de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular_padre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numero de celular del padre '),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ciudad_A',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ciudad de residencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion_A',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='direccion de residencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email_madre',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo electronico de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email_padre',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo electronico del padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_expedicion_madre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='lugar de expedicion de la cedula de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_expedicion_padre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='lugar de expedicion de la cedula del padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_completo_madre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre completo de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_completo_padre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre completo del padre'),
        ),
    ]
