# Generated by Django 4.1 on 2022-09-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0004_alter_profesor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nivel", options={"verbose_name_plural": "niveles"},
        ),
    ]
