# Generated by Django 3.2.9 on 2022-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0005_auto_20221007_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_madre',
            field=models.IntegerField(blank=True, max_length=18, null=True, unique=True, verbose_name='numero de cedula de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_padre',
            field=models.IntegerField(blank=True, max_length=18, null=True, unique=True, verbose_name='numero de cedula del padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.IntegerField(max_length=10, verbose_name='numero de celular'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular_madre',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='numero de celular de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular_padre',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='numero de celular del padre '),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.IntegerField(max_length=18, unique=True, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_contactoE',
            field=models.IntegerField(max_length=10, verbose_name='telefono del contacto de emergencia'),
        ),
    ]
