# Generated by Django 4.1 on 2022-10-21 15:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0009_alter_estudiante_fecha_nacimiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diaClase",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("1", "Lunes"),
                            ("2", "Martes"),
                            ("3", "Miércoles"),
                            ("4", "Jueves"),
                            ("5", "Viernes"),
                            ("6", "Sábado"),
                            ("0", "Domingo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("inicioClase", models.DateField()),
                ("finClase", models.DateField()),
                ("horaClase", models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name="registro",
            name="calendario",
            field=models.ForeignKey(
                db_column="calendario_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Estudiantes_Profesores.calendario",
                verbose_name="calendario",
            ),
        ),
    ]
