# Generated by Django 3.2.9 on 2022-10-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0009_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='firma',
            new_name='exoneracion',
        ),
    ]
