# Generated by Django 3.2.9 on 2022-10-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0011_auto_20221021_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='calendario',
            field=models.ForeignKey(blank=True, db_column='calendario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Estudiantes_Profesores.calendario', verbose_name='calendario'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='profesor',
            field=models.ForeignKey(db_column='profesor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiantes_Profesores.profesor', verbose_name='profesor del estudiante'),
        ),
    ]
