# Generated by Django 3.2.9 on 2022-10-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0013_auto_20221021_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='diaClase',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='finClase',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='horaClase',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='inicioClase',
        ),
    ]
