# Generated by Django 3.2.9 on 2022-10-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0015_registro_inicioclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='calendario',
        ),
        migrations.AddField(
            model_name='calendario',
            name='registro',
            field=models.ForeignKey(blank=True, db_column='calendario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Estudiantes_Profesores.registro', verbose_name='calendario'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='diaClase',
            field=models.TextField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('0', 'Domingo')], max_length=10),
        ),
    ]
