# Generated by Django 3.2.9 on 2022-10-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0016_auto_20221021_1505'),
        ('Estudiantes_Profesores', '0017_rename_firma_estudiante_exoneracion'),
    ]

    operations = [
    ]
