# Generated by Django 3.2.9 on 2022-10-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Picaderos', '0012_alter_picadero_nivel'),
        ('Estudiantes_Profesores', '0018_merge_20221024_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='picadero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Picaderos.picadero'),
        ),
    ]
