# Generated by Django 3.2.9 on 2022-10-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0021_remove_registro_inicioclase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='registro',
            field=models.ForeignKey(blank=True, db_column='registro_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Estudiantes_Profesores.registro', verbose_name='registro'),
        ),
    ]
