# Generated by Django 3.2.9 on 2022-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0022_alter_calendario_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
