# Generated by Django 3.2.9 on 2022-11-02 17:31

import Estudiantes_Profesores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0023_calendario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='documento_A',
            field=models.FileField(upload_to=Estudiantes_Profesores.models.guardar_documento, validators=[Estudiantes_Profesores.models.validar_extencion_archivo]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='exoneracion',
            field=models.FileField(upload_to=Estudiantes_Profesores.models.guardar_exoneracion, validators=[Estudiantes_Profesores.models.validar_extencion_archivo]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='seguro_A',
            field=models.FileField(upload_to=Estudiantes_Profesores.models.guardar_seguro, validators=[Estudiantes_Profesores.models.validar_extencion_archivo]),
        ),
    ]
