# Generated by Django 3.2.9 on 2022-11-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0029_auto_20221102_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='facturacion_electronica',
            field=models.BooleanField(default=False),
        ),
    ]
