# Generated by Django 3.2.9 on 2022-11-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0030_estudiante_facturacion_electronica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre del servicio')),
                ('descripcion', models.CharField(blank=True, max_length=1, null=True, verbose_name='Descripción del servicio')),
                ('tipo', models.BooleanField(verbose_name='Si es verdadero es Mensualidad sino es Esporadica')),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='facturacion_electronica',
            field=models.BooleanField(default=False, verbose_name='¿Desea facturación electrónica?'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiantes_Profesores.servicio'),
        ),
    ]
