# Generated by Django 4.1 on 2022-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0031_auto_20221109_1501"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicio",
            name="tipo",
        ),
        migrations.AddField(
            model_name="servicio",
            name="tipo_clase",
            field=models.CharField(
                choices=[("1", "Clase puntual"), ("2", "Mensualidad")],
                default=1,
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
