# Generated by Django 3.2.9 on 2022-11-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0034_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_clase',
        ),
    ]
