# Generated by Django 4.1 on 2022-12-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0036_servicio_tipo_clase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="documento",
            field=models.BigIntegerField(
                unique=True, verbose_name="numero de documento"
            ),
        ),
    ]
