# Generated by Django 4.1 on 2022-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Estudiantes_Profesores",
            "0039_estudiante_primer_apellido_estudiante_primer_nombre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="primer_apellido",
            field=models.CharField(max_length=50, verbose_name="Primer apellido"),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="primer_nombre",
            field=models.CharField(max_length=50, verbose_name="Primer nombre"),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="segundo_apellido",
            field=models.CharField(max_length=50, verbose_name="Segundo apellido"),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="segundo_nombre",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Segundo nombre"
            ),
        ),
    ]
