# Generated by Django 4.1 on 2022-12-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0040_alter_estudiante_primer_apellido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="barrio_A",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="ciudad_A",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="direccion_A",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="lugar_expedicion_madre",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="lugar_expedicion_padre",
        ),
    ]
