# Generated by Django 4.1 on 2022-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0041_remove_estudiante_barrio_a_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="direccion_facturar",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="direccion"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="email_facturar",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="identificacion_facturar",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="numero de cédula o nit a facturar",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="nombre_facturar",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="nombre completo a facturar",
            ),
        ),
    ]
