# Generated by Django 4.1 on 2022-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0042_estudiante_direccion_facturar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="cedula_madre",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="número de cédula de la madre",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="cedula_padre",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="número de cédula del padre",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="celular",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="número de celular"
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="celular_madre",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="número de celular de la madre"
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="celular_padre",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="número de celular del padre "
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="direccion",
            field=models.CharField(
                max_length=500, verbose_name="dirección de residencia"
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="direccion_facturar",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="dirección"
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="documento",
            field=models.BigIntegerField(
                unique=True, verbose_name="número de documento"
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email_facturar",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Correo electrónico a facturar",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email_madre",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="correo electrónico de la madre",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email_padre",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="correo electrónico del padre",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="identificacion_facturar",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="número de cédula o nit a facturar",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="nombre_contactoE",
            field=models.CharField(
                max_length=100, verbose_name="nombre del contacto de emergencia"
            ),
        ),
    ]
