# Generated by Django 4.1 on 2022-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0043_alter_estudiante_cedula_madre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="autorizaClub",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
