# Generated by Django 4.1 on 2022-12-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudiantes_Profesores", "0044_estudiante_autorizaclub"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="nota",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Notas"
            ),
        ),
    ]
