# Generated by Django 3.2.9 on 2022-12-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0045_estudiante_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='trabaja_sabado',
        ),
    ]
