# Generated by Django 3.2.9 on 2022-12-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0047_auto_20221222_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('1', 'Asistió'), ('2', 'No asistió'), ('3', 'Cancelo con excusa'), ('4', 'Cancelo por enfermedad'), ('0', 'Por validar')], default=0, max_length=15),
        ),
    ]
