# Generated by Django 3.2.9 on 2023-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0051_estudiante_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='exoneracion',
            field=models.BooleanField(default=False),
        ),
    ]
