# Generated by Django 3.2.9 on 2023-01-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0053_auto_20230105_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_madre',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='número de cédula de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_padre',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='número de cédula del padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.IntegerField(blank=True, null=True, verbose_name='número de celular'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular_madre',
            field=models.IntegerField(blank=True, null=True, verbose_name='número de celular de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular_padre',
            field=models.IntegerField(blank=True, null=True, verbose_name='número de celular del padre '),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion_facturar',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='número de cédula o nit a facturar'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_contactoE',
            field=models.IntegerField(verbose_name='telefono del contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_facturar',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='teléfono a facturar'),
        ),
    ]
