# Generated by Django 3.2.9 on 2023-01-06 19:24

import Estudiantes_Profesores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0054_alter_estudiante_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='documento_A',
            field=models.FileField(blank=True, null=True, upload_to=Estudiantes_Profesores.models.guardar_documento, validators=[Estudiantes_Profesores.models.validar_extencion_archivo]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='seguro_A',
            field=models.FileField(blank=True, null=True, upload_to=Estudiantes_Profesores.models.guardar_seguro, validators=[Estudiantes_Profesores.models.validar_extencion_archivo]),
        ),
    ]
