# Generated by Django 3.2.9 on 2023-01-05 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0055_auto_20230105_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_cancelacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='razon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
