# Generated by Django 3.2.9 on 2023-01-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_Profesores', '0055_auto_20230106_1424'),
        ('Estudiantes_Profesores', '0056_auto_20230105_1431'),
    ]

    operations = [
    ]
