# Generated by Django 3.2.9 on 2022-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=150, unique=True)),
                ('color_fondo', models.CharField(max_length=30, verbose_name='color de fondo')),
                ('color_letra', models.CharField(default='rgb(0,0,0)', max_length=30, verbose_name='color de texto')),
            ],
            options={
                'verbose_name_plural': 'niveles',
                'db_table': 'niveles',
            },
        ),
    ]
